In [14]:
from typing import NamedTuple, List
import numpy as np
import pandas as pd

from QLearning import QLearning
from src.utils.utils import create_q_table_frame, show_table, \
                            show_optimal_policy
from src.RL.q_learning.action import Actions

import os
os.chdir("../")

## test

### n=3

In [2]:
snakes = [(3, 8)]
ladders = None # [(3, 8)]

n = 3

game = QLearning(n=n, snakes=snakes, ladders=ladders, log=True, alpha=0.5, p=0.7, lambda_=1)
game.run(n_iter=200)
# create_q_table_frame(game)

In [3]:
show_optimal_policy(game)

1       right_1
2       right_2
3            up
4        left_2
5        left_2
6            up
7       right_2
8    snake_down
9     terminate
dtype: object

In [4]:
create_q_table_frame(game)

up  right_1  right_2  left_1  left_2  down  ladder_up  snake_down  \
1     NaN    1.675   -3.692  -4.015  -3.750   NaN        NaN         NaN   
2     NaN   -3.330   17.662  -3.376  -3.676   NaN        NaN         NaN   
3  45.736   -2.891   -3.562  -2.946  -3.102   NaN        NaN         NaN   
4     NaN   -2.923   20.879  -2.278  62.058   NaN        NaN         NaN   
5     NaN   -2.289   -2.738  -1.625  -1.500   NaN        NaN         NaN   
6  86.670   -1.125   -2.174  -1.000  -1.500   NaN        NaN         NaN   
7     NaN   -1.739   96.949  -1.000  41.922   NaN        NaN         NaN   
8     NaN      NaN      NaN     NaN     NaN   NaN        NaN      -2.988   
9     NaN      NaN      NaN     NaN     NaN   NaN        NaN         NaN   

   terminate  
1        NaN  
2        NaN  
3        NaN  
4        NaN  
5        NaN  
6        NaN  
7        NaN  
8        NaN  
9      100.0

In [5]:
show_table(game.n)
print(f"\nsnakes: \n", game.snakes, end="\n\n")
print(f"ladders: \n", game.ladders)

print("\n---Best Path---")
game.show_path()

[[7 8 9]
 [6 5 4]
 [1 2 3]]

snakes: 
 [(3, 8)]

ladders: 
 None

---Best Path---
1 right_1
2 right_2
3 up
4 left_2
6 up
7 right_2


### n=4

In [6]:
# snakes = [(8, 10)]
# ladders = [(6, 12)]

ladders = [(3, 12), (4, 9)]
snakes = [(2, 14), (2, 6)]
n = 4

game = QLearning(n=n, snakes=snakes, ladders=ladders, log=True, alpha=0.5, p=0.7)
game.run(n_iter=2000)
create_q_table_frame(game)

up  right_1  right_2  left_1  left_2  down  ladder_up  snake_down  \
1      NaN   -0.688   97.000  -1.000  95.500   NaN        NaN         NaN   
2      NaN   97.500   -0.750  96.000   0.000   NaN        NaN         NaN   
3      NaN      NaN      NaN     NaN     NaN   NaN       98.5         NaN   
4      NaN      NaN      NaN     NaN     NaN   NaN        1.0         NaN   
5      NaN   93.500   -2.343  94.500  -1.656   NaN        NaN         NaN   
6      NaN      NaN      NaN     NaN     NaN   NaN        NaN        95.5   
7      NaN   -1.219   -1.000  -0.750  -0.750   NaN        NaN         NaN   
8   -1.625   -0.500   -1.610  -0.500  -0.750   NaN        NaN         NaN   
9      NaN   -3.300   -3.367  -3.000  -3.000   NaN        NaN         NaN   
10     NaN   -2.918   34.896  -2.953  -3.156   NaN        NaN         NaN   
11     NaN   -2.601   -2.656  -3.094  -2.969   NaN        NaN         NaN   
12  96.500   -2.500   -2.828  -2.492  -2.609   NaN        NaN         NaN   
13     NaN   -1.625   96.000  -1.500  97.500   NaN        NaN         NaN   
14     NaN      NaN      NaN     NaN     NaN   NaN        NaN        95.5   
15     NaN   94.500   -1.406  99.000  -0.750   NaN        NaN         NaN   
16     NaN      NaN      NaN     NaN     NaN   NaN        NaN         NaN   

    terminate  
1         NaN  
2         NaN  
3         NaN  
4         NaN  
5         NaN  
6         NaN  
7         NaN  
8         NaN  
9         NaN  
10        NaN  
11        NaN  
12        NaN  
13        NaN  
14        NaN  
15        NaN  
16      100.0

In [9]:
show_table(game.n)
print(f"\nsnakes: \n", game.snakes, end="\n\n")
print(f"ladders: \n", game.ladders)

print("\n---Best Path---")
game.show_path()

[[16 15 14 13]
 [ 9 10 11 12]
 [ 8  7  6  5]
 [ 1  2  3  4]]

snakes: 
 [(2, 14), (2, 6)]

ladders: 
 [(3, 12), (4, 9)]

---Best Path---
1 right_2
3 ladder_up
12 up
13 left_2
15 left_1


In [10]:
show_optimal_policy(game)


1        right_2
2        right_1
3      ladder_up
4      ladder_up
5         left_1
6     snake_down
7         left_1
8        right_1
9         left_1
10       right_2
11       right_1
12            up
13        left_2
14    snake_down
15        left_1
16     terminate
dtype: object

___

### n=5

In [11]:
ladders = [(9, 18), (14, 20)]
snakes = [(2, 12), (7, 16)]
n = 5

game = QLearning(n=n, snakes=snakes, ladders=ladders, log=True, alpha=0.5, p=0.7, epsilon_greedy=True)
game.run(n_iter=2000)
# create_q_table_frame(game)

In [14]:
show_table(game.n)
print(f"\nsnakes: \n", game.snakes, end="\n\n")
print(f"ladders: \n", game.ladders)

print("\n---Best Path---")
game.show_path()

[[21 22 23 24 25]
 [20 19 18 17 16]
 [11 12 13 14 15]
 [10  9  8  7  6]
 [ 1  2  3  4  5]]

snakes: 
 [(2, 12), (7, 16)]

ladders: 
 [(9, 18), (14, 20)]

---Best Path---
1 right_2
3 right_2
5 up
6 left_1
7 left_2
9 ladder_up
18 left_2
20 up
21 right_2
23 right_2


### n=7

#### without epsilon_greedy

In [15]:
ladders = [(9, 18), 
           (21, 35),
           (28, 42)]

snakes = [
    (5, 17),
    (19, 33),
    (25, 47),
]

n = 7

game = QLearning(n=n, snakes=snakes, ladders=ladders, log=True, alpha=0.5, p=0.7, epsilon_greedy=False)
game.run(n_iter=3000)
# create_q_table_frame(game)

In [17]:
show_table(game.n)
print(f"\nsnakes: \n", game.snakes, end="\n\n")
print(f"ladders: \n", game.ladders)

print("\n---Best Path---")
game.show_path()

[[43 44 45 46 47 48 49]
 [42 41 40 39 38 37 36]
 [29 30 31 32 33 34 35]
 [28 27 26 25 24 23 22]
 [15 16 17 18 19 20 21]
 [14 13 12 11 10  9  8]
 [ 1  2  3  4  5  6  7]]

snakes: 
 [(5, 17), (19, 33), (25, 47)]

ladders: 
 [(9, 18), (21, 35), (28, 42)]

---Best Path---
1 right_2
3 right_2
5 right_2
7 up
8 left_1
9 ladder_up
18 right_2
20 right_1
21 ladder_up
35 up
36 left_1
37 left_1
38 left_2
40 left_2
42 up
43 right_2
45 right_1
46 right_2
48 right_2


#### with epsilon-greedy

In [11]:
ladders = [(9, 18), 
           (21, 35),
           (28, 42)]

snakes = [
    (5, 17),
    (19, 33),
    (25, 47),
]

n = 7

game = QLearning(n=n, snakes=snakes, ladders=ladders, log=True, alpha=0.5, p=0.7, epsilon_greedy=True)
game.run(n_iter=3000)
# create_q_table_frame(game)

In [12]:
show_table(game.n)
print(f"\nsnakes: \n", game.snakes, end="\n\n")
print(f"ladders: \n", game.ladders)

print("\n---Best Path---")
game.show_path()

[[43 44 45 46 47 48 49]
 [42 41 40 39 38 37 36]
 [29 30 31 32 33 34 35]
 [28 27 26 25 24 23 22]
 [15 16 17 18 19 20 21]
 [14 13 12 11 10  9  8]
 [ 1  2  3  4  5  6  7]]

snakes: 
 [(5, 17), (19, 33), (25, 47)]

ladders: 
 [(9, 18), (21, 35), (28, 42)]

---Best Path---
1 right_2
3 right_2
5 right_2
7 up
8 left_1
9 ladder_up
18 right_2
20 right_2
21 ladder_up
35 up
36 left_1
37 left_2
39 left_1
40 left_2
42 up
43 right_1
44 right_2
46 right_2
48 right_2


## adding epsilon-greedy feature

In [2]:
epsilon = 0.8
results = []
for _ in range(100) :
    v = 0 if np.random.rand() > epsilon else 1
    results.append(v)

In [11]:
minmax_scale(np.arange(1, 100)).round(3)

array([0.   , 0.01 , 0.02 , 0.031, 0.041, 0.051, 0.061, 0.071, 0.082,
       0.092, 0.102, 0.112, 0.122, 0.133, 0.143, 0.153, 0.163, 0.173,
       0.184, 0.194, 0.204, 0.214, 0.224, 0.235, 0.245, 0.255, 0.265,
       0.276, 0.286, 0.296, 0.306, 0.316, 0.327, 0.337, 0.347, 0.357,
       0.367, 0.378, 0.388, 0.398, 0.408, 0.418, 0.429, 0.439, 0.449,
       0.459, 0.469, 0.48 , 0.49 , 0.5  , 0.51 , 0.52 , 0.531, 0.541,
       0.551, 0.561, 0.571, 0.582, 0.592, 0.602, 0.612, 0.622, 0.633,
       0.643, 0.653, 0.663, 0.673, 0.684, 0.694, 0.704, 0.714, 0.724,
       0.735, 0.745, 0.755, 0.765, 0.776, 0.786, 0.796, 0.806, 0.816,
       0.827, 0.837, 0.847, 0.857, 0.867, 0.878, 0.888, 0.898, 0.908,
       0.918, 0.929, 0.939, 0.949, 0.959, 0.969, 0.98 , 0.99 , 1.   ])

In [9]:
sigmoid(np.arange(1, 100)).round(3)

array([0.731, 0.881, 0.953, 0.982, 0.993, 0.998, 0.999, 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ])

In [8]:
softmax(np.arange(1, 100)).round(3)

array([0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.001, 0.002, 0.004, 0.012, 0.031, 0.086, 0.233, 0.632])

In [14]:
minmax_scale(np.arange(100))[::-1]

array([1.        , 0.98989899, 0.97979798, 0.96969697, 0.95959596,
       0.94949495, 0.93939394, 0.92929293, 0.91919192, 0.90909091,
       0.8989899 , 0.88888889, 0.87878788, 0.86868687, 0.85858586,
       0.84848485, 0.83838384, 0.82828283, 0.81818182, 0.80808081,
       0.7979798 , 0.78787879, 0.77777778, 0.76767677, 0.75757576,
       0.74747475, 0.73737374, 0.72727273, 0.71717172, 0.70707071,
       0.6969697 , 0.68686869, 0.67676768, 0.66666667, 0.65656566,
       0.64646465, 0.63636364, 0.62626263, 0.61616162, 0.60606061,
       0.5959596 , 0.58585859, 0.57575758, 0.56565657, 0.55555556,
       0.54545455, 0.53535354, 0.52525253, 0.51515152, 0.50505051,
       0.49494949, 0.48484848, 0.47474747, 0.46464646, 0.45454545,
       0.44444444, 0.43434343, 0.42424242, 0.41414141, 0.4040404 ,
       0.39393939, 0.38383838, 0.37373737, 0.36363636, 0.35353535,
       0.34343434, 0.33333333, 0.32323232, 0.31313131, 0.3030303 ,
       0.29292929, 0.28282828, 0.27272727, 0.26262626, 0.25252

___

## GUI  
**NOT COMPLETED**


In [13]:
# import matplotlib.pyplot as plt
# import numpy as np
# import time 
# from IPython import display

# n = 4
# snakes = [(2, 14)]
# ladders = [(3, 15)]
# # snakes_loc = [(QLearning.state_to_loc(state[0], n=N), QLearning.state_to_loc(state[1], n=N)) for state in snakes]
# # ladders_loc = [(QLearning.state_to_loc(state[0], n=N), QLearning.state_to_loc(state[1], n=N)) for state in ladders]

# game = QLearning(n=n, snakes=snakes, ladders=ladders, log=True, alpha=0.5, p=0.7)
# # show_game((0, 0), N)

# for l in game._run_simulation(n_iter=10) :
#     time.sleep(1)
#     print(l)
#     # print(game.loc_to_state(l, N))
#     show_game(l, n)
#     display.clear_output(wait=True)
#     # input()
# # plt.show()

In [14]:
# show_table(N)

In [15]:
# def show_game(loc, N) :
#     # Create figure 
#     # Draw N x N grid
#     fig, ax = plt.subplots()
#     ax.grid(True, which='both', linestyle='-', linewidth=1)
#     ax.set_xticks(np.arange(0, N+1));
#     ax.set_yticks(np.arange(0, N+1));
#     circle = plt.Circle((0, N), 0.2, color='black')  
#     ax.add_artist(circle)
    
#     ax.arrow(
#         x=2.5, y=0.5,
#         dx=-1 ,dy=3,
#         color="blue",
#         head_width = 0.1,  
#         head_length = 0.1,
#     )

#     ax.arrow(
#         x=2.5, y=3.5,
#         dx=-1 ,dy=-3,
#         color="red",
#         head_width = 0.1,  
#         head_length = 0.1,
#     )

#     ax.add_patch(plt.Rectangle((0, 3), 0.95, 0.95, facecolor='green')) # exit state

#     ax.set_xlim(0, N)
#     ax.set_ylim(0, N)

#     x, y = loc
#     circle.center = (x+0.5, y+0.5)
#     # fig.canvas.draw()
#     plt.show()

## Final test

- minimum possible move is : `12`

### without epsilon_greedy

In [12]:
snakes = [(42,96), (71,94), (32,75), (16,47), (10,25), (3,37)]
ladders = [(54,88), (41,79), (22,58), (14,55), (12,50), (4,56)]

n = 10
game = QLearning(n=n, snakes=snakes, ladders=ladders, log=True, alpha=0.5, p=0.7, epsilon_greedy=False)
game.run(n_iter=20_000)
# create_q_table_frame(game)

In [3]:
show_table(game.n)
print(f"\nsnakes: \n", game.snakes, end="\n\n")
print(f"ladders: \n", game.ladders)

show_optimal_policy(game)

[[100  99  98  97  96  95  94  93  92  91]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 20  19  18  17  16  15  14  13  12  11]
 [  1   2   3   4   5   6   7   8   9  10]]

snakes: 
 [(42, 96), (71, 94), (32, 75), (16, 47), (10, 25), (3, 37)]

ladders: 
 [(54, 88), (41, 79), (22, 58), (14, 55), (12, 50), (4, 56)]


1         right_1
2         right_2
3         right_1
4       ladder_up
5         right_1
          ...    
96     snake_down
97         left_1
98         left_2
99         left_2
100     terminate
Length: 100, dtype: object

In [4]:
create_q_table_frame(game)

up  right_1  right_2  left_1  left_2  down  ladder_up  snake_down  \
1   NaN   90.000   -4.680  89.000  -4.858   NaN        NaN         NaN   
2   NaN   -3.883   91.000  -4.577  88.500   NaN        NaN         NaN   
3   NaN   91.500   -3.476  90.000  -5.720   NaN        NaN         NaN   
4   NaN      NaN      NaN     NaN     NaN   NaN       92.5         NaN   
5   NaN   -2.478   -2.750  -4.148  -2.907   NaN        NaN         NaN   
..   ..      ...      ...     ...     ...   ...        ...         ...   
96  NaN      NaN      NaN     NaN     NaN   NaN        NaN        84.0   
97  NaN   83.000   -3.058  97.500  -1.125   NaN        NaN         NaN   
98  NaN   -0.750   82.500  -0.500  98.500   NaN        NaN         NaN   
99  NaN   -0.500    0.000   0.000  48.875   NaN        NaN         NaN   
100 NaN      NaN      NaN     NaN     NaN   NaN        NaN         NaN   

     terminate  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
..         ...  
96         NaN  
97         NaN  
98         NaN  
99         NaN  
100      100.0  

[100 rows x 9 columns]

In [8]:
game.show_path()

1 right_1
2 right_2
4 ladder_up
56 right_1
55 right_1
54 ladder_up
88 right_2
90 up
91 left_2
93 left_2
95 left_2
97 left_1
98 left_2


In [25]:
# import pickle
# with open('/answer_qtable.pickle', 'wb') as f:
#     pickle.dump(game.q_table, f)



In [27]:
# # Load Q-table
# with open('answer_qtable.pickle', 'rb') as f:
#    loaded_qtable = pickle.load(f)

In [24]:
game.complete_cycle

422

### with epsilon_greedy

In [9]:
snakes = [(42,96), (71,94), (32,75), (16,47), (10,25), (3,37)]
ladders = [(54,88), (41,79), (22,58), (14,55), (12,50), (4,56)]

n = 10
game = QLearning(n=n, snakes=snakes, ladders=ladders, log=True, alpha=0.5, p=0.7, epsilon_greedy=True)
game.run(n_iter=8000)
# create_q_table_frame(game)

In [10]:
create_q_table_frame(game)

up  right_1  right_2  left_1  left_2  down  ladder_up  snake_down  \
1   NaN   90.500   -4.187  89.500  -4.970   NaN        NaN         NaN   
2   NaN   -3.414   91.500  -3.375  89.000   NaN        NaN         NaN   
3   NaN   92.000   -3.712  90.500  -3.714   NaN        NaN         NaN   
4   NaN      NaN      NaN     NaN     NaN   NaN       93.0         NaN   
5   NaN   -2.550   -2.534  -2.830  -4.434   NaN        NaN         NaN   
..   ..      ...      ...     ...     ...   ...        ...         ...   
96  NaN      NaN      NaN     NaN     NaN   NaN        NaN      81.581   
97  NaN   80.005   -1.375  97.500  -0.750   NaN        NaN         NaN   
98  NaN   11.438   78.366  -0.500  98.500   NaN        NaN         NaN   
99  NaN   -0.500    0.000   0.000  -0.750   NaN        NaN         NaN   
100 NaN      NaN      NaN     NaN     NaN   NaN        NaN         NaN   

     terminate  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
..         ...  
96         NaN  
97         NaN  
98         NaN  
99         NaN  
100      100.0  

[100 rows x 9 columns]

In [12]:
game.show_path()

1 right_1
2 right_2
4 ladder_up
56 right_2
54 ladder_up
88 right_2
90 up
91 left_2
93 left_2
95 left_2
97 left_1
98 left_2


the resulta are better with even less iterations !!! 🙂💃🏼  
the path we found is actually the optimum path with the least steps possible

In [12]:
# import pickle

# with open('answer_qtable(epsilon-greedy).pickle', 'wb') as f:
#     pickle.dump(game.q_table, f)


___

In [ ]:
ladders = [(1, 24), (6, 99), (13, 55), (29, 71), (67, 88)]
snakes = [(8, 31), (15, 97), (66, 87), (8, 42)]


In [18]:
snakes = [(2,12), (11,14), (4,17), (19,31), (22,35)]
ladders = [(5,7), (18,20), (15,25), (21,32)]
n = 6
game = QLearning(n=n, snakes=snakes, ladders=ladders, log=True, alpha=0.5, p=0.7, epsilon_greedy=True)
game.run(n_iter=8000)

In [19]:
show_table(game.n)
print(f"\nsnakes: \n", game.snakes, end="\n\n")
print(f"ladders: \n", game.ladders)

show_optimal_policy(game)

[[36 35 34 33 32 31]
 [25 26 27 28 29 30]
 [24 23 22 21 20 19]
 [13 14 15 16 17 18]
 [12 11 10  9  8  7]
 [ 1  2  3  4  5  6]]

snakes: 
 [(2, 12), (11, 14), (4, 17), (19, 31), (22, 35)]

ladders: 
 [(5, 7), (18, 20), (15, 25), (21, 32)]


1        right_2
2        right_2
3        right_1
4        right_2
5      ladder_up
6         left_1
7         left_1
8        right_1
9         left_1
10       right_1
11        left_1
12    snake_down
13       right_1
14    snake_down
15     ladder_up
16       right_1
17    snake_down
18     ladder_up
19       right_1
20       right_1
21     ladder_up
22       right_1
23       right_1
24            up
25       right_1
26       right_1
27       right_1
28       right_1
29       right_1
30            up
31    snake_down
32       right_1
33       right_1
34       right_1
35    snake_down
36     terminate
dtype: object

In [21]:
create_q_table_frame(game)

up  right_1  right_2  left_1  left_2  down  ladder_up  snake_down  \
1      NaN  -81.712  -81.237 -81.586 -81.900   NaN        NaN         NaN   
2      NaN  -81.476  -81.267 -81.541 -81.683   NaN        NaN         NaN   
3      NaN  -81.057  -81.252 -81.064 -81.498   NaN        NaN         NaN   
4      NaN  -80.913  -80.527 -80.832 -80.698   NaN        NaN         NaN   
5      NaN      NaN      NaN     NaN     NaN   NaN    -80.632         NaN   
6  -81.927  -80.312  -80.720 -80.226 -80.470   NaN        NaN         NaN   
7      NaN  -83.866  -83.945 -83.376 -83.592   NaN        NaN         NaN   
8      NaN  -82.914  -84.420 -83.184 -83.000   NaN        NaN         NaN   
9      NaN  -82.936  -82.989 -82.800 -83.257   NaN        NaN         NaN   
10     NaN  -82.716  -83.398 -82.809 -82.778   NaN        NaN         NaN   
11     NaN  -83.332  -82.595 -82.408 -83.141   NaN        NaN         NaN   
12     NaN      NaN      NaN     NaN     NaN   NaN        NaN     -82.739   
13     NaN    0.000    0.000   0.000   0.000   NaN        NaN         NaN   
14     NaN      NaN      NaN     NaN     NaN   NaN        NaN       0.000   
15     NaN      NaN      NaN     NaN     NaN   NaN      0.000         NaN   
16     NaN    0.000    0.000   0.000   0.000   NaN        NaN         NaN   
17     NaN      NaN      NaN     NaN     NaN   NaN        NaN       0.000   
18     NaN      NaN      NaN     NaN     NaN   NaN      0.000         NaN   
19     NaN    0.000    0.000   0.000   0.000   NaN        NaN         NaN   
20     NaN    0.000    0.000   0.000   0.000   NaN        NaN         NaN   
21     NaN      NaN      NaN     NaN     NaN   NaN      0.000         NaN   
22     NaN    0.000    0.000   0.000   0.000   NaN        NaN         NaN   
23     NaN    0.000    0.000   0.000   0.000   NaN        NaN         NaN   
24   0.000    0.000    0.000   0.000   0.000   NaN        NaN         NaN   
25     NaN    0.000    0.000   0.000   0.000   NaN        NaN         NaN   
26     NaN    0.000    0.000   0.000   0.000   NaN        NaN         NaN   
27     NaN    0.000    0.000   0.000   0.000   NaN        NaN         NaN   
28     NaN    0.000    0.000   0.000   0.000   NaN        NaN         NaN   
29     NaN    0.000    0.000   0.000   0.000   NaN        NaN         NaN   
30   0.000    0.000    0.000   0.000   0.000   NaN        NaN         NaN   
31     NaN      NaN      NaN     NaN     NaN   NaN        NaN       0.000   
32     NaN    0.000    0.000   0.000   0.000   NaN        NaN         NaN   
33     NaN    0.000    0.000   0.000   0.000   NaN        NaN         NaN   
34     NaN    0.000    0.000   0.000   0.000   NaN        NaN         NaN   
35     NaN      NaN      NaN     NaN     NaN   NaN        NaN       0.000   
36     NaN      NaN      NaN     NaN     NaN   NaN        NaN         NaN   

    terminate  
1         NaN  
2         NaN  
3         NaN  
4         NaN  
5         NaN  
6         NaN  
7         NaN  
8         NaN  
9         NaN  
10        NaN  
11        NaN  
12        NaN  
13        NaN  
14        NaN  
15        NaN  
16        NaN  
17        NaN  
18        NaN  
19        NaN  
20        NaN  
21        NaN  
22        NaN  
23        NaN  
24        NaN  
25        NaN  
26        NaN  
27        NaN  
28        NaN  
29        NaN  
30        NaN  
31        NaN  
32        NaN  
33        NaN  
34        NaN  
35        NaN  
36        0.0